<?php 
/* @var $user \User\Model\Entity\UserEntity */ 
$short = $this->id2Short($user->getId());
?>
<section id="profile">
	<div class="container">
		<div class="row">
			<div class="col-xs-10 col-sm-6 col-md-5 col-lg-4">
			<label>Id:</label><?=$user->getId()?><br/>
			<label>ShortId:</label>(<?=$this->id2Normal($short)?>) <br/>
			<label>Email:</label><?=$user->getEmail()?><br/>
			<label>Status:</label><?=$user->getStatus()?><br/>
			<label>Username:</label><?=$user->getUserName()?><br/>
			<label>FirstName:</label><?=$user->getFirstName()?><br/>
			<label>LastName:</label><?=$user->getLastName()?><br/>						
			<label>Dob:</label><?=$user->getDob()->format(DateTime::ISO8601)?><br/>
			<label>Gender:</label><?=$user->getGender()?><br/>
			</div>
		</div>
		
		<?php if($this->isAllowed($user, 'edit')) :?>
		<div class="row">
			<div class="col-xs-10 col-sm-6 col-md-5 col-lg-4">
			<li class="active"><a href="<?php echo $this->url('user/profile-edit',['id' => $short]) ?>"><?php echo $this->translate('Edit') ?></a></li>
			</div>
		</div>
		<?php endif; ?>
		
	</div>
</section>
