<?php
/* @var $user \User\Model\Entity\UserEntity */ 
$short = $this->id2Short($user->getId());
use User\Form\FieldSet\UserFieldSet;
$editProfileForm = $this->editProfileForm;
$editProfileForm->setAttribute('action', $this->url(null,array(),array(),true));
$editProfileForm->setAttribute('autocomplete', 'off');
$editProfileForm->prepare();
$fieldSetEdit = $editProfileForm->get(\User\Form\FieldSet\UserFieldSet::NAME);
$validationGroup = $editProfileForm->getValidationGroup();

$openTemplateError = '<div><div class="alert alert-danger" role="alert">';
$closeTemplateError = '</div></div>';
$this->formElementErrors()
    ->setMessageOpenFormat($openTemplateError)
    ->setMessageCloseString($closeTemplateError);
?>
<section id="profile-edit">
	<div class="container">
		<div class="row">
			<div class="col-xs-12 col-sm-4 col-md-3 inPage leftMenu">
			    <div class="list-group">
			    		<a class="list-group-item active" href="<?php echo $this->url('user/profile-edit',['id' => $short]) ?>"><?php echo $this->translate('Edit') ?></a>
			            <a class="list-group-item" href="<?php echo $this->url('user/profile-remove',['id' => $short]) ?>"><?php echo $this->translate('Remove') ?></a>
			    </div>
			</div>		
		
			<div class="col-xs-12 col-sm-8 col-md-5 inPage">
            	<div class="" ></div>
                <?= $this->form()->openTag($editProfileForm); ?>
                <accordion close-others="false">
                <accordion-group heading="<?= ucfirst($this->translate("PROFILE_EDIT_BASIC")) ; ?>" is-open="true" >			
                <div class="form-group">
                    <label><?= ucfirst($this->translate("userName")) ; ?></label>
                	<?php // Render element
                        $element = $fieldSetEdit->get(UserFieldSet::INPUT_NAME_USERNAME);
                        $element->setAttributes(
                            [
                                'class' => 'form-control',
                                'placeholder' => ucfirst($this->translate("userName")),
                                'data-ng-model' => UserFieldSet::INPUT_NAME_USERNAME,
                                'data-ng-init' => UserFieldSet::INPUT_NAME_USERNAME . "='". $element->getValue() ."'",
                                'data-skapp-filter-pattern' => '[0-9A-Za-z_]*',
                                'data-skapp-filter-max-length' => 15,
                                'data-skapp-filter-lowercase' => '',
                            ]
                        );
                        echo $this->formElement($element);
                    ?>
                </div>
                <?= $this->formElementErrors($element); ?>
                
                <div class="form-group">
                    <label for=""><?= ucfirst($this->translate("email")) ; ?></label>
                    <?php
                        $element = $fieldSetEdit->get(UserFieldSet::INPUT_NAME_EMAIL);
                        $element->setAttributes(
                            [
                                'class' => 'form-control',
                                'placeholder' => ucfirst($this->translate("email"))
                            ]
                        );
                        echo $this->formElement($element);
                    ?>
                </div>
                <?= $this->formElementErrors($element); ?>                
                
                <div class="form-group">
                    <label for=""><?= ucfirst($this->translate("firstName")) ; ?></label>
                    <?php
                        $element = $fieldSetEdit->get(UserFieldSet::INPUT_NAME_FIRST_NAME);
                        $element->setAttributes(
                            [
                                'class' => 'form-control',
                                'placeholder' => ucfirst($this->translate("firstName"))
                            ]
                        );
                        echo $this->formElement($element);
                    ?>
                </div>
                <?= $this->formElementErrors($element); ?>                
                
                <div class="form-group">
                    <label for=""><?= ucfirst($this->translate("lastName")) ; ?></label>
                    <?php
                        $element = $fieldSetEdit->get(UserFieldSet::INPUT_NAME_LAST_NAME);
                        $element->setAttributes(
                            [
                                'class' => 'form-control',
                                'placeholder' => ucfirst($this->translate("lastName"))
                            ]
                        );
                        echo $this->formElement($element);
                    ?>
                </div>
                <?= $this->formElementErrors($element); ?>                
                
                <div class="form-group">
                    <label for=""><?= ucfirst($this->translate("gender")) ; ?></label>
                    <?php
                        $element = $fieldSetEdit->get(UserFieldSet::INPUT_NAME_GENDER);
                        $element->setAttributes(
                            [
                                'class' => 'form-control',
                                'placeholder' => ucfirst($this->translate("gender"))
                            ]
                        );
                        echo $this->formElement($element);
                    ?>
                </div>
                <?= $this->formElementErrors($element); ?>                
                
                <div class="form-group" data-ng-controller="DatePickerController">
                    <label for=""><?= ucfirst($this->translate("dob")) ; ?></label>
                    <div class="input-group">
                    <?php
                        $element = $fieldSetEdit->get(UserFieldSet::INPUT_NAME_DOB);
                        $element->setAttributes(
                            [
                                'class' => 'form-control',
                                //'placeholder' => ucfirst($this->translate("dob")),
								'data-datepicker-popup'=>"dd-MM-yyyy",
								'data-ng-model'=>"dt",
								'data-is-open'=>"opened"
                            ]
                        );
                        echo $this->formElement($element);
                    ?>
                    <span class="input-group-addon" ng-click="open($event)">
                	<i class="fa fa-calendar"></i>
                	</span>
                	</div>
                </div>
                <?= $this->formElementErrors($element); ?>                
                </accordion-group>
                
                <?php if($this->isAllowed($user, 'edit-roles')) :?>
	                <accordion-group heading="<?= ucfirst($this->translate("PROFILE_EDIT_ROLES")) ; ?>" is-open="false">
	                <div class="form-group" id="rolesCollection">
	                    <label for=""><?= ucfirst($this->translate("roles")) ; ?></label>
	                    <?php //Collection
	                        $element = $fieldSetEdit->get('roles');
	                        echo $this->formElement($element);
	                    ?>
	                </div>
	                <div>
	                	<button data-add-item data-id="rolesCollection">Add a new role</button>
	                	<button data-remove-item data-id="rolesCollection">Remove role</button>
	                </div>
	                
	                </accordion-group>
                <?php endif; ?>
                
                </accordion>
                
                <button type="submit" class="btn btn-border btn-profile-edit btn-block btn-lg">
                    <?= ucfirst($this->translate("SAVE")) ; ?>
                </button>
                <?= $this->form()->closeTag(); ?>                
                
			</div>
		</div>
	</div><!-- /container -->
</section>