<?php
$this->flashMessenger()->setMessageOpenFormat('<div%s>
     <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
         &times;
     </button>
     ')
    ->setMessageSeparatorString('<br/>')
    ->setMessageCloseString('</div>');
echo $this->flashMessenger()->render('error',   array('alert', 'alert-dismissable', 'alert-danger'));
echo $this->flashMessenger()->render('info',    array('alert', 'alert-dismissable', 'alert-info'));
echo $this->flashMessenger()->render('success', array('alert', 'alert-dismissable', 'alert-success'));
?>