<?php 
/* @var $user \User\Model\Entity\UserEntity */ 
/* @var $item \Application\Model\Entity\ItemEntity */
use Zend\Debug\Debug;
$this->registrationForm->setAttribute('action', '');
?>

<div class="row">
    <div class="col-xs-12">
        <h1>Users</h1>
    </div>
    <div class="col-xs-12">
        <ul class="fa-ul">
        <?php foreach ($this->users as $user) :?>
          <li><i class="fa-li fa fa-square"></i>
          <?= $user->getId()?> - <?= $user->getEmail()?> - <?= $user->getDateCreated()->format(DateTime::ISO8601)?>
          <?//= Debug::dump($user->getAddress())?> - <?//= Debug::dump($user->getRoles()->getArrayCopy()) ?>

          </li>
        <?php endforeach;?>
        <?php echo $this->paginationControl($this->users, 'Sliding', 'pagination/default'); ?>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-xs-12">
        <h1>Items for user</h1>
    </div>
    <div class="col-xs-12">
        <ul class="fa-ul">
        <?php foreach ($this->items as $item) :?>
          <li><i class="fa-li fa fa-square"></i>
          <?= $item->getId()?> - <?= $item->getUserId()?> - <?= $user->getDateCreated()->format(DateTime::ISO8601)?>
          </li>
        <?php endforeach;?>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-xs-12">
        <h1>Form</h1>
    </div>
    <div class="col-xs-12">
    <?php $this->registrationForm->add(array(
            'name' => 'path',
            'type' => 'file',
            'options' => array(
                'label' => 'Photo',
            ),
        ));?>    
    <?php $this->registrationForm->add(array(
             'name' => 'submit',
             'attributes' => array(
                 'type' => 'submit',
                 'value' => 'Submit',
             ),
         ))?>
	<?php echo $this->form($this->registrationForm) ?>	
    </div>
</div>
<div class="row">
	<div class="col-xs-12">
	<img alt="" src="/images?i=/funny-baby-evil-plan-face.jpg&r=original" />
	<img alt="" src="/images?i=/funny-baby-evil-plan-face.jpg&r=thumbmaxi" />
	<img alt="" src="/images?i=/funny-baby-evil-plan-face.jpg&r=thumb" />
	<img alt="" src="/images?i=missing&r=original" />
	</div>
</div>
