<?php
/**
 * Configuration file generated by ZFTool
 * The previous configuration file is stored in application.config.old
 *
 * @see https://github.com/zendframework/ZFTool
 */
return array(
    'modules' => array(
    	'ZF\DevelopmentMode',
   		'BjyAuthorize',	
        'AsseticBundle',
        'HangerSnippet',
        'Matryoshka',
        'SphinxSearch',
    	'MailMan',	
        'Application',
        'AuthModule',
        'User'
    ),
    'module_listener_options' => array(
        'module_paths' => array(
            './module',
            './vendor'
        ),
        'config_glob_paths' => array(
            'config/autoload/{,*.}{global,local}.php'
        ),
        'config_cache_enabled' => false,
        'config_cache_key' => 'module_config_cache',
        'module_map_cache_enabled' => false,
        'module_map_cache_key' => 'module_map_config_cache',
        'cache_dir' => './data/cache',
        'check_dependencies' => false,    		
    )
);
