<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Application Title'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' =>  '/img/favicon.ico')); ?>
        <?php echo $this->headLink()->prependStylesheet($this->basePath('/_/asset/application/css/application.css')); ?>

        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE9]>
        <script src="<?=$this->basePath('/_/asset/application/js/html5shiv.min.js')?>"></script>
        <script src="<?=$this->basePath('/_/asset/application/js/respond.min.js')?>"></script>
        <![endif]-->
        <?php echo $this->headScript();?>

    </head>
    <body ng-app="application">
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>">&nbsp;<?php echo $this->translate('Skeleton Application') ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class=""><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                        <?php if($this->identity()) :?>
	                        <?php 
	                        $sm = $this->getHelperPluginManager()->getServiceLocator();
	                        $user = $sm->get('AuthModule\AuthenticationService')->getIdentityObject(); ?>
	                        <li class=""><a href="<?php echo $this->url('user-home') ?>"><?php echo $this->translate('User Home') ?></a></li>
	                        <li class=""><a href="<?php echo $this->url('user/profile',['id' =>$this->id2Short($user->getId())]) ?>">
	                        	<?php echo $this->translate('Profile') ?></a>
	                        </li>
	                        
	                        <?php if($this->isAllowed('route/user/admin')) :?>
	                        <li class=""><a href="<?php echo $this->url('user/admin') ?>"><?php echo $this->translate('AdminOnly') ?></a></li>
	                        <?php endif; ?>
	                        <?=$this->partial('user/partials/navbar-dropdown-menu.phtml')?>
	                        <li class=""><a href="<?php echo $this->url('user/logout') ?>"><?php echo $this->translate('Logout') ?></a></li>
                        <?php else :?>
                        
	                        <li class=""><a href="<?php echo $this->url('login') ?>"><?php echo $this->translate('Login') ?></a></li>
	                        <li class=""><a href="<?php echo $this->url('registration') ?>"><?php echo $this->translate('Registration') ?></a></li>
                        <?php endif; ?>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="nav-padding"></div>
        <main id="wrapper">
	        <div class="container mainContainer">
	            <?php echo $this->content; ?>
	        </div> <!-- /container -->
        </main>
        <div class="footer-container">
	        <footer id="footer" class="container">
		        <div class="row">
					<section class="footer-block col-xs-12 col-sm-3" ng-controller="CollapseController">
						<h4 ng-click="isCollapsed = !isCollapsed">Block1</h4>
						<ul collapse="isCollapsed">
							<li class="first_item"><a href="#" title="Link1">Link1</a></li>
							<li class="item"><a href="#" title="Link1">Link1</a></li>
						</ul>
					</section>
					<section class="footer-block col-xs-12 col-sm-3" ng-controller="CollapseController">
						<h4 ng-click="isCollapsed = !isCollapsed">Block2</h4>
						<ul collapse="isCollapsed">
							<li class="first_item"><a href="#" title="Link1">Link1</a></li>
						</ul>					
					</section>
					<section class="footer-block col-xs-12 col-sm-3" ng-controller="CollapseController">
						<h4 ng-click="isCollapsed = !isCollapsed">Block3</h4>
						<ul collapse="isCollapsed">
							<li class="first_item"><a href="#" title="Link1">Link1</a></li>
						</ul>					
					</section>
					<section class="footer-block col-xs-12 col-sm-3" ng-controller="CollapseController">
						<h4 ng-click="isCollapsed = !isCollapsed">Block4</h4>
						<ul collapse="isCollapsed">
							<li class="first_item"><a href="#" title="Link1">Link1</a></li>
						</ul>					
					</section>												        
		        </div>
	        </footer>
        </div>        
        <?php echo $this->hangerSnippet() ?>
        <?php echo $this->inlineScript()->prependFile($this->basePath('/_/asset/application/js/application.js')); ?>
    </body>
</html>